services:
  tftp:
    build:
      dockerfile: tftp.Dockerfile
      args:
        - BOOT_URL=http://${API_IP}/netboot.ipxe
        - COMMIT_SHA=be3a78eaf804a2c437aa055d5c1e2f4a1310a0c1
    ports:
      - 69:69/udp
    networks:
      vlan:
        ipv4_address: ${TFTP_IP}
    depends_on:
      - api

  api:
    build:
      dockerfile: api.Dockerfile
      args:
        - PRESEED_URL=http://${API_IP}/preseed.cfg
        - SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}
        - DISK_PATH=/dev/vda
        - HOST_NAME=${HOST_NAME}
        - VG_NAME=${VG_NAME}
        - MAIN_PARTITION_SIZE=10 GB
        - DEBIAN_MIRROR_HOST=deb.debian.org
    networks:
      vlan:
        ipv4_address: ${API_IP}

networks:
  vlan:
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE}
    ipam:
      config:
        - subnet: ${SUBNET_CIDR}
          gateway: ${GATEWAY_IP}
