---
- name: Disable k0s service
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  failed_when: false
  with_items:
    - k0scontroller
    - k0sworker

- name: Umount k0s filesystems
  ansible.builtin.include_tasks: umount_with_children.yml
  with_items:
    - "{{ k0s_remove_data_dir }}"
    - "{{ k0s_remove_libexec_dir }}"
  loop_control:
    loop_var: mounted_fs

- name: Remove k0s Directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ k0s_remove_config_dir }}"
    - "{{ k0s_remove_data_dir }}"
    - "{{ k0s_remove_libexec_dir }}"
    - /var/lib/kubelet
    - "{{ k0s_remove_systemd_dir }}/k0scontroller.service"
    - "{{ k0s_remove_systemd_dir }}/k0sworker.service"

- name: Daemon reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
