---
- name: Get the list of mounted filesystems
  become: true
  ansible.builtin.shell: >
    set -o pipefail
    && cat /proc/mounts
    | awk '{ print $2}'
    | grep -E "^{{ mounted_fs }}"
  register: get_mounted_filesystems
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: get_mounted_filesystems.stdout | length > 0

- name: Umount filesystem
  become: true
  ansible.posix.mount:
    path: "{{ item }}"
    state: unmounted
  with_items: "{{ get_mounted_filesystems.stdout_lines }}"
