---
- name: Read existing k0s configuration
  register: existing_k0s_config_slurp
  ansible.builtin.slurp:
    src: "{{ k0s_config_edit_config_path }}"
- name: Decode and parse existing k0s configuration
  ansible.builtin.set_fact:
    existing_k0s_data: >
      {{ existing_k0s_config_slurp.content | b64decode | from_yaml }}
- name: Merge desired changes with existing configuration
  ansible.builtin.set_fact:
    merged_k0s_data: >
      {{ existing_k0s_data | combine(k0s_config_edit_config_changes, recursive=True) }}
- name: Write the merged configuration back to the file
  become: true
  ansible.builtin.copy:
    content: "{{ merged_k0s_data | to_nice_yaml(indent=2) }}"
    dest: "{{ k0s_config_edit_config_path }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
- name: Enable and check k0s service
  become: true
  ansible.builtin.systemd:
    name: k0scontroller
    daemon_reload: true
    state: restarted
    enabled: true
