- name: Add Docker's official GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "644"
- name: Add Docker repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ architecture }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - python3-venv
      - python3-pip
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker
